### ISSUE TITLE
Social links are hard to find, maybe resize Muatex logo?

### ISSUE THREAD

**Issue by Xenoxide** [Muatex/muatexwebsite-v1#1]
The only place I see the links are at the top of the page, in the logos. But the issue is the giant Muatex logo at the beginning of the page catches all the attention, and moves it away from the social logos. It also means that you have to scroll down in order to find any useful information at all, because of the logo taking up the whole screen. This is not efficient for someone who just wants the links. A design like [this](https://disq.me/u/muatex) might be better for that, but I assume you want to keep the overall page structure.

Anyway point is every time I open the website looking for the links, I scroll the whole website, then I go back to the top and realize it was above the logo

**Comment by Xenoxide** [comment]
sorry this is two issues i put it in one for some reason

**Comment by Muatex** [comment]
### Done!
Thanks for the suggestion! 8)
